version: '3.9'

services:
  db:
    image: mysql:8.0-debian
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: agiledev
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose:
      - 3307
    networks:
      agiledev-network:
  agile_dev-projects:
    image: joel37/agile-dev-projects
    restart: always
    build: .
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://${DB_HOST:-db}:3307/agile_dev?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: root
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - agiledev-network
networks:
  agiledev-network:
    driver: bridge