
server:
  port: 8080

spring:
  application:
    name: AGILY_DEV_PROJECTS
  datasource:
    url: jdbc:mysql://${DB_HOST:agiledev.c6sgkh4frdqs.us-east-1.rds.amazonaws.com}:3307/agiledev?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME:docker}
    password: ${DB_PASSWORD:rootroot}
  flyway:
    locations: classpath:db/migration,classpath:db/testdata
    baselineOnMigrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob.non-contextual-creation: true
    jackson:
      deserialization:
        fail-on-unknown-properties: true
        fail-on-ignored-properties: true
    mvc:
      throw-exception-if-no-handler-found: true
    logging:
      level:
        root: INFO
        org.springframework.web: DEBUG
  logging:
    file:
      path: /app/logs




